name: Sean Merrow
markdown: kramdown
defaults:
  -
    scope:
      path: "_posts" 
    values:
      layout: "posts"
  -
    scope:
      path: "about" 
    values:
      layout: "posts"
permalink: /blog/:year/:month/:day/:title
